### ISSUE TITLE
Support version 3.3

### ISSUE THREAD

**Issue by kahwooi** [hypriot/rpi-alpine-scratch#2]
When it is going to update to Alpine 3.3?

**Comment by atomi** [comment]
Just change edge to 3.3 in https://github.com/hypriot/rpi-alpine-scratch/blob/master/mkimage-alpine.sh#L72

**Comment by firecyberice** [comment]
A better way is making a PR changing 
https://github.com/hypriot/rpi-alpine-scratch/blob/master/VERSION#L1 and
https://github.com/hypriot/rpi-alpine-scratch/blob/master/.drone.yml#L30

**Comment by funkyfuture** [comment]
meanwhile Alpine 3.4 is released. can i be of any help?

**Comment by firecyberice** [comment]
I just updated the repo.
Now version 3.3 3.4 and edge are available
